### ISSUE TITLE
clutch fails to run on iOS 8.1

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [KJCracks/Clutch#66]
i get this error when i execute clutch. all the perms are correct so i am not sure why it fails..

clutch -c
## Clutch 1.4.6

dyld: lazy symbol binding failed: Symbol not found: _MobileInstallationLookup
  Referenced from: /usr/bin/clutch
  Expected in: /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation

dyld: Symbol not found: _MobileInstallationLookup
  Referenced from: /usr/bin/clutch
  Expected in: /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation

i am using 1.4.6 Release

not sure about the Dev Builds if they support 64 bit..

1.4.7-git2 seems to be working on iOS 8.1 iPhone 5s

but 1.4.6 <-- not working
